apiVersion: v2
appVersion: "1.0"
description: A Helm chart for ccpay bulkscanning payments api
name: ccpay-bulkscanning-api
home: https://github.com/hmcts/ccpay-bulkscanning-app
version: 1.0.28
maintainers:
  - name: HMCTS Fees and Pay team
dependencies:
  - name: java
    version: 5.2.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
