apiVersion: v1
appVersion: "1.0"
description: A Helm chart for ccpay bulkscanning payments api
name: ccpay-bulkscanning-api
home: https://github.com/hmcts/ccpay-bulkscanning-app
version: 1.0.6
maintainers:
  - name: HMCTS Fees and Pay team
